# Generated by Django 6.0 on 2025-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_pedido_numero_pedido_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='63554F78AF', max_length=20, unique=True),
        ),
    ]
