# Generated by Django 6.0 on 2025-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='DA3E3410BE', max_length=20, unique=True),
        ),
    ]
