# Generated by Django 6.0 on 2025-12-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='0112CD6068', max_length=20, unique=True),
        ),
    ]
